# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e2470d31357f376b284319a7f998c288ec0dcfce22fd7c7f57803a4d328feeab226a2c215ebc7021594feeb90b8bf3af9861e50dfc9da158aa97263b7b46eae

test:
  secret_key_base: 4b99d53ad022821c9e5ee921cc3c920b834b482b18ae2678dba6d0cce556c3ff54a4e830af49904b7390a714ea3509e3d1f648c308716f3a6d4322e983e504a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
